openapi: 3.0.4

info:

  title: Todo App

  description: |-
    This is a sample todo app REST API.

  version: 0.0.1

servers:

  - url: http://locahhost:8080/api/v1

tags:

  - name: user
    description: Operations for user

paths:

  /users:

    post:
      tags:
        - user
      summary: Create new user.
      description: Create new user.
      security:
        - ApiKeyAuth: []
        - OAuth2:
            - read
            - write
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   400
                code:     invalidParameters
                message:  error message
                type:     error

        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   401
                code:     Unauthorized
                message:  User is not authorized
                type:     error
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   403
                code:     Forbidden
                message:  User does not have required permissions
                type:     error
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   404
                code:     Not found
                message:  Not found
                type:     error
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   500
                code:     Internal server error
                message:  Internal server error
                type:     error

    get:
      tags:
        - user
      summary: Get all user.
      description: Returns list of user.
      security:
        - ApiKeyAuth: []
        - OAuth2:
            - read
            - write
      parameters:
        - in: query
          name: sort
          schema:
            type: string
            enum:
              - first_name
              - last_name
            default: first_name
          description: The property to sort the results by.
        - in: query
          name: direction
          schema:
            type: string
            enum:
              - asc
              - desc
            default: asc
          description: The order to sort by.
        - in: query
          name: per_page
          schema:
            type: integer
            default: 10
          description: The number of results per page.
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: The page number of the results to fetch.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   400
                code:     invalidParameters
                message:  error message
                type:     error

        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   401
                code:     Unauthorized
                message:  User is not authorized
                type:     error
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   403
                code:     Forbidden
                message:  User does not have required permissions
                type:     error
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   404
                code:     Not found
                message:  Not found
                type:     error
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   500
                code:     Internal server error
                message:  Internal server error
                type:     error

  /users/{id}:

    get:
      tags:
        - user
      summary: Get a specific user.
      description: Get a specific user.
      security:
        - ApiKeyAuth: []
        - OAuth2:
            - read
            - write
      parameters:
        - name: id
          in: path
          description: ID of user
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   400
                code:     invalidParameters
                message:  error message
                type:     error

        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   401
                code:     Unauthorized
                message:  User is not authorized
                type:     error
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   403
                code:     Forbidden
                message:  User does not have required permissions
                type:     error
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   404
                code:     Not found
                message:  Not found
                type:     error
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   500
                code:     Internal server error
                message:  Internal server error
                type:     error

    put:
      tags:
        - user
      summary: Create or replace user.
      description: Create or replace user.
      security:
        - ApiKeyAuth: []
        - OAuth2:
            - read
            - write
      parameters:
        - name: id
          in: path
          description: ID of user
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
            example:
              firstName: Vivek
              lastName: Sinha
              email: vivek.sinha@microsoft.com
              country: USA
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                id: 10,
                firstName: Vivek
                lastName: Sinha
                email: vivek.sinha@microsoft.com
                gender: null
                city: null
                country: USA
                created_at: 2025-07-21T17:32:28Z
                updated_at: 2025-08-21T17:32:28Z
                links:
                  self: selfLink

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   400
                code:     invalidParameters
                message:  error message
                type:     error

        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   401
                code:     Unauthorized
                message:  User is not authorized
                type:     error
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   403
                code:     Forbidden
                message:  User does not have required permissions
                type:     error
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   404
                code:     Not found
                message:  Not found
                type:     error
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   500
                code:     Internal server error
                message:  Internal server error
                type:     error

    patch:
      tags:
        - user
      summary: Update specified fields.
      description: Update specified fields.
      security:
        - ApiKeyAuth: []
        - OAuth2:
            - read
            - write
      parameters:
        - name: id
          in: path
          description: ID of user
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
            example:
              email: vivek.sinha@microsoft.com
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                id: 10,
                firstName: Vivek
                lastName: Sinha
                email: vivek.sinha@microsoft.com
                gender: MALE
                city: New york
                country: USA
                created_at: 2025-07-21T17:32:28Z
                updated_at: 2025-08-21T17:32:28Z
                links:
                  self: selfLink

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   400
                code:     invalidParameters
                message:  error message
                type:     error

        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   401
                code:     Unauthorized
                message:  User is not authorized
                type:     error
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   403
                code:     Forbidden
                message:  User does not have required permissions
                type:     error
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   404
                code:     Not found
                message:  Not found
                type:     error
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   500
                code:     Internal server error
                message:  Internal server error
                type:     error

    delete:
      tags:
        - user
      summary: Delete user.
      description: Delete user.
      security:
        - ApiKeyAuth: []
        - OAuth2:
            - read
            - write
      parameters:
        - name: id
          in: path
          description: ID of user
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: User deleted successfully.
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   400
                code:     invalidParameters
                message:  error message
                type:     error

        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   401
                code:     Unauthorized
                message:  User is not authorized
                type:     error
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   403
                code:     Forbidden
                message:  User does not have required permissions
                type:     error
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   404
                code:     Not found
                message:  Not found
                type:     error
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status:   500
                code:     Internal server error
                message:  Internal server error
                type:     error

components:

  securitySchemes:

    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations

  schemas:

    UserRequest:
      type: object
      properties:
        firstName:
          type: string
          example: Vivek
        lastName:
          type: string
          example: Sinha
        email:
          type: string
          format: email
          example: vivek.sinha@google.com
        gender:
          type: string
          enum: [MALE, FEMALE, OTHER]
          example: MALE
        city:
          type: string
          example: New york
        country:
          type: string
          example: USA

    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        firstName:
          type: string
          example: Vivek
        lastName:
          type: string
          example: Sinha
        email:
          type: string
          format: email
          example: vivek.sinha@google.com
        gender:
          type: string
          enum: [MALE, FEMALE, OTHER]
          example: MALE
        city:
          type: string
          example: New york
        country:
          type: string
          example: USA
        created_at:
          type: string
          format: date-time
          example: 2025-07-21T17:32:28Z
        updated_at:
          type: string
          format: date-time
          example: 2025-08-21T17:32:28Z
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
              example: selfLink

    Users:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: "#/components/schemas/User"
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
              example: selfLink
            next:
              type: string
              format: uri
              example: nextLink
            prev:
              type: string
              format: uri
              example: prevLink

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          format: int32
          example: 400
        code:
          type: string
          example: invalidParameters
        message:
          type: string
          example: error message
        type:
          type: string
          example: error













